---
- name: My First Playbook
  hosts: linuxservers
  tasks:
    - name: Check uptime
      command: uptime
      register: uptime_result
    - name: Display uptime
      debug:
        msg: "{{ uptime_result.stdout }}"
